language: generic

sudo: required

services: 
    - docker

before_install:
    - docker build -t ravichand3767/docker-react -f "Dockerfile.dev" .
    
script:
    - docker run -e CI=true ravichand3767/docker-react npm run test -- --coverage